// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package accumulator

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// AccumulatorClient is the client API for Accumulator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccumulatorClient interface {
	// Append a new hash
	Append(ctx context.Context, in *Hash, opts ...grpc.CallOption) (*ID, error)
	Get(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Hash, error)
	Search(ctx context.Context, in *Hash, opts ...grpc.CallOption) (*ID, error)
	GetDigest(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Hash, error)
	GetProofByID(ctx context.Context, in *ID, opts ...grpc.CallOption) (*HashProof, error)
	GetProofByHash(ctx context.Context, in *Hash, opts ...grpc.CallOption) (*HashProof, error)
}

type accumulatorClient struct {
	cc grpc.ClientConnInterface
}

func NewAccumulatorClient(cc grpc.ClientConnInterface) AccumulatorClient {
	return &accumulatorClient{cc}
}

func (c *accumulatorClient) Append(ctx context.Context, in *Hash, opts ...grpc.CallOption) (*ID, error) {
	out := new(ID)
	err := c.cc.Invoke(ctx, "/accumulator.Accumulator/Append", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accumulatorClient) Get(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Hash, error) {
	out := new(Hash)
	err := c.cc.Invoke(ctx, "/accumulator.Accumulator/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accumulatorClient) Search(ctx context.Context, in *Hash, opts ...grpc.CallOption) (*ID, error) {
	out := new(ID)
	err := c.cc.Invoke(ctx, "/accumulator.Accumulator/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accumulatorClient) GetDigest(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Hash, error) {
	out := new(Hash)
	err := c.cc.Invoke(ctx, "/accumulator.Accumulator/GetDigest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accumulatorClient) GetProofByID(ctx context.Context, in *ID, opts ...grpc.CallOption) (*HashProof, error) {
	out := new(HashProof)
	err := c.cc.Invoke(ctx, "/accumulator.Accumulator/GetProofByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accumulatorClient) GetProofByHash(ctx context.Context, in *Hash, opts ...grpc.CallOption) (*HashProof, error) {
	out := new(HashProof)
	err := c.cc.Invoke(ctx, "/accumulator.Accumulator/GetProofByHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccumulatorServer is the server API for Accumulator service.
// All implementations must embed UnimplementedAccumulatorServer
// for forward compatibility
type AccumulatorServer interface {
	// Append a new hash
	Append(context.Context, *Hash) (*ID, error)
	Get(context.Context, *ID) (*Hash, error)
	Search(context.Context, *Hash) (*ID, error)
	GetDigest(context.Context, *Empty) (*Hash, error)
	GetProofByID(context.Context, *ID) (*HashProof, error)
	GetProofByHash(context.Context, *Hash) (*HashProof, error)
	mustEmbedUnimplementedAccumulatorServer()
}

// UnimplementedAccumulatorServer must be embedded to have forward compatible implementations.
type UnimplementedAccumulatorServer struct {
}

func (UnimplementedAccumulatorServer) Append(context.Context, *Hash) (*ID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Append not implemented")
}
func (UnimplementedAccumulatorServer) Get(context.Context, *ID) (*Hash, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedAccumulatorServer) Search(context.Context, *Hash) (*ID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedAccumulatorServer) GetDigest(context.Context, *Empty) (*Hash, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDigest not implemented")
}
func (UnimplementedAccumulatorServer) GetProofByID(context.Context, *ID) (*HashProof, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProofByID not implemented")
}
func (UnimplementedAccumulatorServer) GetProofByHash(context.Context, *Hash) (*HashProof, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProofByHash not implemented")
}
func (UnimplementedAccumulatorServer) mustEmbedUnimplementedAccumulatorServer() {}

// UnsafeAccumulatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccumulatorServer will
// result in compilation errors.
type UnsafeAccumulatorServer interface {
	mustEmbedUnimplementedAccumulatorServer()
}

func RegisterAccumulatorServer(s grpc.ServiceRegistrar, srv AccumulatorServer) {
	s.RegisterService(&_Accumulator_serviceDesc, srv)
}

func _Accumulator_Append_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Hash)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccumulatorServer).Append(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accumulator.Accumulator/Append",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccumulatorServer).Append(ctx, req.(*Hash))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accumulator_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccumulatorServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accumulator.Accumulator/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccumulatorServer).Get(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accumulator_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Hash)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccumulatorServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accumulator.Accumulator/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccumulatorServer).Search(ctx, req.(*Hash))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accumulator_GetDigest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccumulatorServer).GetDigest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accumulator.Accumulator/GetDigest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccumulatorServer).GetDigest(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accumulator_GetProofByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccumulatorServer).GetProofByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accumulator.Accumulator/GetProofByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccumulatorServer).GetProofByID(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accumulator_GetProofByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Hash)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccumulatorServer).GetProofByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accumulator.Accumulator/GetProofByHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccumulatorServer).GetProofByHash(ctx, req.(*Hash))
	}
	return interceptor(ctx, in, info, handler)
}

var _Accumulator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "accumulator.Accumulator",
	HandlerType: (*AccumulatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Append",
			Handler:    _Accumulator_Append_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Accumulator_Get_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _Accumulator_Search_Handler,
		},
		{
			MethodName: "GetDigest",
			Handler:    _Accumulator_GetDigest_Handler,
		},
		{
			MethodName: "GetProofByID",
			Handler:    _Accumulator_GetProofByID_Handler,
		},
		{
			MethodName: "GetProofByHash",
			Handler:    _Accumulator_GetProofByHash_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accumulator.proto",
}
