// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: accumulator/accumulator.proto

package accumulator

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ID) Reset() {
	*x = ID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accumulator_accumulator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ID) ProtoMessage() {}

func (x *ID) ProtoReflect() protoreflect.Message {
	mi := &file_accumulator_accumulator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ID.ProtoReflect.Descriptor instead.
func (*ID) Descriptor() ([]byte, []int) {
	return file_accumulator_accumulator_proto_rawDescGZIP(), []int{0}
}

func (x *ID) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Hash struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *Hash) Reset() {
	*x = Hash{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accumulator_accumulator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hash) ProtoMessage() {}

func (x *Hash) ProtoReflect() protoreflect.Message {
	mi := &file_accumulator_accumulator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hash.ProtoReflect.Descriptor instead.
func (*Hash) Descriptor() ([]byte, []int) {
	return file_accumulator_accumulator_proto_rawDescGZIP(), []int{1}
}

func (x *Hash) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type HashProof struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash   []byte      `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Digest []byte      `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	Path   []*HashNode `protobuf:"bytes,3,rep,name=path,proto3" json:"path,omitempty"`
}

func (x *HashProof) Reset() {
	*x = HashProof{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accumulator_accumulator_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HashProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashProof) ProtoMessage() {}

func (x *HashProof) ProtoReflect() protoreflect.Message {
	mi := &file_accumulator_accumulator_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashProof.ProtoReflect.Descriptor instead.
func (*HashProof) Descriptor() ([]byte, []int) {
	return file_accumulator_accumulator_proto_rawDescGZIP(), []int{2}
}

func (x *HashProof) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *HashProof) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *HashProof) GetPath() []*HashNode {
	if x != nil {
		return x.Path
	}
	return nil
}

type HashNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Left bool   `protobuf:"varint,1,opt,name=left,proto3" json:"left,omitempty"`
	Hash []byte `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *HashNode) Reset() {
	*x = HashNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accumulator_accumulator_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HashNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashNode) ProtoMessage() {}

func (x *HashNode) ProtoReflect() protoreflect.Message {
	mi := &file_accumulator_accumulator_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashNode.ProtoReflect.Descriptor instead.
func (*HashNode) Descriptor() ([]byte, []int) {
	return file_accumulator_accumulator_proto_rawDescGZIP(), []int{3}
}

func (x *HashNode) GetLeft() bool {
	if x != nil {
		return x.Left
	}
	return false
}

func (x *HashNode) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accumulator_accumulator_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_accumulator_accumulator_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_accumulator_accumulator_proto_rawDescGZIP(), []int{4}
}

var File_accumulator_accumulator_proto protoreflect.FileDescriptor

var file_accumulator_accumulator_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x61, 0x63, 0x63, 0x75, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x61, 0x63,
	0x63, 0x75, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0b, 0x61, 0x63, 0x63, 0x75, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x14, 0x0a, 0x02,
	0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x1a, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61,
	0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22, 0x62,
	0x0a, 0x09, 0x48, 0x61, 0x73, 0x68, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x12, 0x0a, 0x04, 0x68,
	0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12,
	0x16, 0x0a, 0x06, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x06, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x63, 0x63, 0x75, 0x6d, 0x75, 0x6c, 0x61,
	0x74, 0x6f, 0x72, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x22, 0x32, 0x0a, 0x08, 0x48, 0x61, 0x73, 0x68, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x6c, 0x65,
	0x66, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32,
	0xdb, 0x01, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x75, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x12,
	0x2e, 0x0a, 0x06, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x12, 0x11, 0x2e, 0x61, 0x63, 0x63, 0x75,
	0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x1a, 0x0f, 0x2e, 0x61,
	0x63, 0x63, 0x75, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x49, 0x44, 0x22, 0x00, 0x12,
	0x2b, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x0f, 0x2e, 0x61, 0x63, 0x63, 0x75, 0x6d, 0x75, 0x6c,
	0x61, 0x74, 0x6f, 0x72, 0x2e, 0x49, 0x44, 0x1a, 0x11, 0x2e, 0x61, 0x63, 0x63, 0x75, 0x6d, 0x75,
	0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x09,
	0x47, 0x65, 0x74, 0x44, 0x69, 0x67, 0x65, 0x73, 0x74, 0x12, 0x12, 0x2e, 0x61, 0x63, 0x63, 0x75,
	0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x11, 0x2e,
	0x61, 0x63, 0x63, 0x75, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x48, 0x61, 0x73, 0x68,
	0x22, 0x00, 0x12, 0x39, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x42, 0x79,
	0x49, 0x44, 0x12, 0x0f, 0x2e, 0x61, 0x63, 0x63, 0x75, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72,
	0x2e, 0x49, 0x44, 0x1a, 0x16, 0x2e, 0x61, 0x63, 0x63, 0x75, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f,
	0x72, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x22, 0x00, 0x42, 0x19, 0x5a,
	0x17, 0x75, 0x70, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x63, 0x63,
	0x75, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_accumulator_accumulator_proto_rawDescOnce sync.Once
	file_accumulator_accumulator_proto_rawDescData = file_accumulator_accumulator_proto_rawDesc
)

func file_accumulator_accumulator_proto_rawDescGZIP() []byte {
	file_accumulator_accumulator_proto_rawDescOnce.Do(func() {
		file_accumulator_accumulator_proto_rawDescData = protoimpl.X.CompressGZIP(file_accumulator_accumulator_proto_rawDescData)
	})
	return file_accumulator_accumulator_proto_rawDescData
}

var file_accumulator_accumulator_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_accumulator_accumulator_proto_goTypes = []interface{}{
	(*ID)(nil),        // 0: accumulator.ID
	(*Hash)(nil),      // 1: accumulator.Hash
	(*HashProof)(nil), // 2: accumulator.HashProof
	(*HashNode)(nil),  // 3: accumulator.HashNode
	(*Empty)(nil),     // 4: accumulator.Empty
}
var file_accumulator_accumulator_proto_depIdxs = []int32{
	3, // 0: accumulator.HashProof.path:type_name -> accumulator.HashNode
	1, // 1: accumulator.Accumulator.Append:input_type -> accumulator.Hash
	0, // 2: accumulator.Accumulator.Get:input_type -> accumulator.ID
	4, // 3: accumulator.Accumulator.GetDigest:input_type -> accumulator.Empty
	0, // 4: accumulator.Accumulator.GetProofByID:input_type -> accumulator.ID
	0, // 5: accumulator.Accumulator.Append:output_type -> accumulator.ID
	1, // 6: accumulator.Accumulator.Get:output_type -> accumulator.Hash
	1, // 7: accumulator.Accumulator.GetDigest:output_type -> accumulator.Hash
	2, // 8: accumulator.Accumulator.GetProofByID:output_type -> accumulator.HashProof
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_accumulator_accumulator_proto_init() }
func file_accumulator_accumulator_proto_init() {
	if File_accumulator_accumulator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_accumulator_accumulator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accumulator_accumulator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hash); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accumulator_accumulator_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HashProof); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accumulator_accumulator_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HashNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accumulator_accumulator_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_accumulator_accumulator_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_accumulator_accumulator_proto_goTypes,
		DependencyIndexes: file_accumulator_accumulator_proto_depIdxs,
		MessageInfos:      file_accumulator_accumulator_proto_msgTypes,
	}.Build()
	File_accumulator_accumulator_proto = out.File
	file_accumulator_accumulator_proto_rawDesc = nil
	file_accumulator_accumulator_proto_goTypes = nil
	file_accumulator_accumulator_proto_depIdxs = nil
}
