// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.6
// source: accumulator.proto

package accumulator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ID) Reset() {
	*x = ID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accumulator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ID) ProtoMessage() {}

func (x *ID) ProtoReflect() protoreflect.Message {
	mi := &file_accumulator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ID.ProtoReflect.Descriptor instead.
func (*ID) Descriptor() ([]byte, []int) {
	return file_accumulator_proto_rawDescGZIP(), []int{0}
}

func (x *ID) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Hash struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *Hash) Reset() {
	*x = Hash{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accumulator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hash) ProtoMessage() {}

func (x *Hash) ProtoReflect() protoreflect.Message {
	mi := &file_accumulator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hash.ProtoReflect.Descriptor instead.
func (*Hash) Descriptor() ([]byte, []int) {
	return file_accumulator_proto_rawDescGZIP(), []int{1}
}

func (x *Hash) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type HashProof struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash   []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Digest []byte   `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	Path   [][]byte `protobuf:"bytes,3,rep,name=path,proto3" json:"path,omitempty"`
}

func (x *HashProof) Reset() {
	*x = HashProof{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accumulator_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HashProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashProof) ProtoMessage() {}

func (x *HashProof) ProtoReflect() protoreflect.Message {
	mi := &file_accumulator_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashProof.ProtoReflect.Descriptor instead.
func (*HashProof) Descriptor() ([]byte, []int) {
	return file_accumulator_proto_rawDescGZIP(), []int{2}
}

func (x *HashProof) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *HashProof) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *HashProof) GetPath() [][]byte {
	if x != nil {
		return x.Path
	}
	return nil
}

type GetOldProofByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Digest []byte `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
}

func (x *GetOldProofByIDRequest) Reset() {
	*x = GetOldProofByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accumulator_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOldProofByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOldProofByIDRequest) ProtoMessage() {}

func (x *GetOldProofByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_accumulator_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOldProofByIDRequest.ProtoReflect.Descriptor instead.
func (*GetOldProofByIDRequest) Descriptor() ([]byte, []int) {
	return file_accumulator_proto_rawDescGZIP(), []int{3}
}

func (x *GetOldProofByIDRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetOldProofByIDRequest) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

type GetOldProofByHashRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash   []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Digest []byte `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
}

func (x *GetOldProofByHashRequest) Reset() {
	*x = GetOldProofByHashRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accumulator_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOldProofByHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOldProofByHashRequest) ProtoMessage() {}

func (x *GetOldProofByHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_accumulator_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOldProofByHashRequest.ProtoReflect.Descriptor instead.
func (*GetOldProofByHashRequest) Descriptor() ([]byte, []int) {
	return file_accumulator_proto_rawDescGZIP(), []int{4}
}

func (x *GetOldProofByHashRequest) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *GetOldProofByHashRequest) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accumulator_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_accumulator_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_accumulator_proto_rawDescGZIP(), []int{5}
}

var File_accumulator_proto protoreflect.FileDescriptor

var file_accumulator_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x63, 0x63, 0x75, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x61, 0x63, 0x63, 0x75, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72,
	0x22, 0x14, 0x0a, 0x02, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1a, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x12, 0x12,
	0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61,
	0x73, 0x68, 0x22, 0x4b, 0x0a, 0x09, 0x48, 0x61, 0x73, 0x68, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x12,
	0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68,
	0x61, 0x73, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x06, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22,
	0x40, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x4f, 0x6c, 0x64, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x42, 0x79,
	0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x69, 0x67,
	0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x64, 0x69, 0x67, 0x65, 0x73,
	0x74, 0x22, 0x46, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x4f, 0x6c, 0x64, 0x50, 0x72, 0x6f, 0x6f, 0x66,
	0x42, 0x79, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73,
	0x68, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x06, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x32, 0xf2, 0x03, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x75, 0x6d, 0x75, 0x6c, 0x61, 0x74,
	0x6f, 0x72, 0x12, 0x2e, 0x0a, 0x06, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x12, 0x11, 0x2e, 0x61,
	0x63, 0x63, 0x75, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x1a,
	0x0f, 0x2e, 0x61, 0x63, 0x63, 0x75, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x49, 0x44,
	0x22, 0x00, 0x12, 0x2b, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x0f, 0x2e, 0x61, 0x63, 0x63, 0x75,
	0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x49, 0x44, 0x1a, 0x11, 0x2e, 0x61, 0x63, 0x63,
	0x75, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x22, 0x00, 0x12,
	0x2e, 0x0a, 0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x11, 0x2e, 0x61, 0x63, 0x63, 0x75,
	0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x1a, 0x0f, 0x2e, 0x61,
	0x63, 0x63, 0x75, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x49, 0x44, 0x22, 0x00, 0x12,
	0x34, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x44, 0x69, 0x67, 0x65, 0x73, 0x74, 0x12, 0x12, 0x2e, 0x61,
	0x63, 0x63, 0x75, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x11, 0x2e, 0x61, 0x63, 0x63, 0x75, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x48,
	0x61, 0x73, 0x68, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x6f,
	0x66, 0x42, 0x79, 0x49, 0x44, 0x12, 0x0f, 0x2e, 0x61, 0x63, 0x63, 0x75, 0x6d, 0x75, 0x6c, 0x61,
	0x74, 0x6f, 0x72, 0x2e, 0x49, 0x44, 0x1a, 0x16, 0x2e, 0x61, 0x63, 0x63, 0x75, 0x6d, 0x75, 0x6c,
	0x61, 0x74, 0x6f, 0x72, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x22, 0x00,
	0x12, 0x3d, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x42, 0x79, 0x48, 0x61,
	0x73, 0x68, 0x12, 0x11, 0x2e, 0x61, 0x63, 0x63, 0x75, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72,
	0x2e, 0x48, 0x61, 0x73, 0x68, 0x1a, 0x16, 0x2e, 0x61, 0x63, 0x63, 0x75, 0x6d, 0x75, 0x6c, 0x61,
	0x74, 0x6f, 0x72, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x22, 0x00, 0x12,
	0x50, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4f, 0x6c, 0x64, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x42, 0x79,
	0x49, 0x44, 0x12, 0x23, 0x2e, 0x61, 0x63, 0x63, 0x75, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72,
	0x2e, 0x47, 0x65, 0x74, 0x4f, 0x6c, 0x64, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x42, 0x79, 0x49, 0x44,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x61, 0x63, 0x63, 0x75, 0x6d, 0x75,
	0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x22,
	0x00, 0x12, 0x54, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4f, 0x6c, 0x64, 0x50, 0x72, 0x6f, 0x6f, 0x66,
	0x42, 0x79, 0x48, 0x61, 0x73, 0x68, 0x12, 0x25, 0x2e, 0x61, 0x63, 0x63, 0x75, 0x6d, 0x75, 0x6c,
	0x61, 0x74, 0x6f, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x6c, 0x64, 0x50, 0x72, 0x6f, 0x6f, 0x66,
	0x42, 0x79, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x61, 0x63, 0x63, 0x75, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x48, 0x61, 0x73, 0x68,
	0x50, 0x72, 0x6f, 0x6f, 0x66, 0x22, 0x00, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x72, 0x61, 0x6e, 0x6b, 0x6f, 0x6e, 0x6c, 0x79, 0x2f,
	0x75, 0x70, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x63, 0x63, 0x75,
	0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_accumulator_proto_rawDescOnce sync.Once
	file_accumulator_proto_rawDescData = file_accumulator_proto_rawDesc
)

func file_accumulator_proto_rawDescGZIP() []byte {
	file_accumulator_proto_rawDescOnce.Do(func() {
		file_accumulator_proto_rawDescData = protoimpl.X.CompressGZIP(file_accumulator_proto_rawDescData)
	})
	return file_accumulator_proto_rawDescData
}

var file_accumulator_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_accumulator_proto_goTypes = []interface{}{
	(*ID)(nil),                       // 0: accumulator.ID
	(*Hash)(nil),                     // 1: accumulator.Hash
	(*HashProof)(nil),                // 2: accumulator.HashProof
	(*GetOldProofByIDRequest)(nil),   // 3: accumulator.GetOldProofByIDRequest
	(*GetOldProofByHashRequest)(nil), // 4: accumulator.GetOldProofByHashRequest
	(*Empty)(nil),                    // 5: accumulator.Empty
}
var file_accumulator_proto_depIdxs = []int32{
	1, // 0: accumulator.Accumulator.Append:input_type -> accumulator.Hash
	0, // 1: accumulator.Accumulator.Get:input_type -> accumulator.ID
	1, // 2: accumulator.Accumulator.Search:input_type -> accumulator.Hash
	5, // 3: accumulator.Accumulator.GetDigest:input_type -> accumulator.Empty
	0, // 4: accumulator.Accumulator.GetProofByID:input_type -> accumulator.ID
	1, // 5: accumulator.Accumulator.GetProofByHash:input_type -> accumulator.Hash
	3, // 6: accumulator.Accumulator.GetOldProofByID:input_type -> accumulator.GetOldProofByIDRequest
	4, // 7: accumulator.Accumulator.GetOldProofByHash:input_type -> accumulator.GetOldProofByHashRequest
	0, // 8: accumulator.Accumulator.Append:output_type -> accumulator.ID
	1, // 9: accumulator.Accumulator.Get:output_type -> accumulator.Hash
	0, // 10: accumulator.Accumulator.Search:output_type -> accumulator.ID
	1, // 11: accumulator.Accumulator.GetDigest:output_type -> accumulator.Hash
	2, // 12: accumulator.Accumulator.GetProofByID:output_type -> accumulator.HashProof
	2, // 13: accumulator.Accumulator.GetProofByHash:output_type -> accumulator.HashProof
	2, // 14: accumulator.Accumulator.GetOldProofByID:output_type -> accumulator.HashProof
	2, // 15: accumulator.Accumulator.GetOldProofByHash:output_type -> accumulator.HashProof
	8, // [8:16] is the sub-list for method output_type
	0, // [0:8] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_accumulator_proto_init() }
func file_accumulator_proto_init() {
	if File_accumulator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_accumulator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accumulator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hash); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accumulator_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HashProof); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accumulator_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOldProofByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accumulator_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOldProofByHashRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accumulator_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_accumulator_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_accumulator_proto_goTypes,
		DependencyIndexes: file_accumulator_proto_depIdxs,
		MessageInfos:      file_accumulator_proto_msgTypes,
	}.Build()
	File_accumulator_proto = out.File
	file_accumulator_proto_rawDesc = nil
	file_accumulator_proto_goTypes = nil
	file_accumulator_proto_depIdxs = nil
}
