// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package accumulator

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// AccumulatorClient is the client API for Accumulator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccumulatorClient interface {
	// Append a new hash
	Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*AppendReply, error)
	ID(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*IDReply, error)
	GetProof(ctx context.Context, in *GetProofRequest, opts ...grpc.CallOption) (*GetProofReply, error)
}

type accumulatorClient struct {
	cc grpc.ClientConnInterface
}

func NewAccumulatorClient(cc grpc.ClientConnInterface) AccumulatorClient {
	return &accumulatorClient{cc}
}

func (c *accumulatorClient) Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*AppendReply, error) {
	out := new(AppendReply)
	err := c.cc.Invoke(ctx, "/accumulator.Accumulator/Append", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accumulatorClient) ID(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*IDReply, error) {
	out := new(IDReply)
	err := c.cc.Invoke(ctx, "/accumulator.Accumulator/ID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accumulatorClient) GetProof(ctx context.Context, in *GetProofRequest, opts ...grpc.CallOption) (*GetProofReply, error) {
	out := new(GetProofReply)
	err := c.cc.Invoke(ctx, "/accumulator.Accumulator/GetProof", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccumulatorServer is the server API for Accumulator service.
// All implementations must embed UnimplementedAccumulatorServer
// for forward compatibility
type AccumulatorServer interface {
	// Append a new hash
	Append(context.Context, *AppendRequest) (*AppendReply, error)
	ID(context.Context, *IDRequest) (*IDReply, error)
	GetProof(context.Context, *GetProofRequest) (*GetProofReply, error)
	mustEmbedUnimplementedAccumulatorServer()
}

// UnimplementedAccumulatorServer must be embedded to have forward compatible implementations.
type UnimplementedAccumulatorServer struct {
}

func (UnimplementedAccumulatorServer) Append(context.Context, *AppendRequest) (*AppendReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Append not implemented")
}
func (UnimplementedAccumulatorServer) ID(context.Context, *IDRequest) (*IDReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ID not implemented")
}
func (UnimplementedAccumulatorServer) GetProof(context.Context, *GetProofRequest) (*GetProofReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProof not implemented")
}
func (UnimplementedAccumulatorServer) mustEmbedUnimplementedAccumulatorServer() {}

// UnsafeAccumulatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccumulatorServer will
// result in compilation errors.
type UnsafeAccumulatorServer interface {
	mustEmbedUnimplementedAccumulatorServer()
}

func RegisterAccumulatorServer(s grpc.ServiceRegistrar, srv AccumulatorServer) {
	s.RegisterService(&_Accumulator_serviceDesc, srv)
}

func _Accumulator_Append_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccumulatorServer).Append(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accumulator.Accumulator/Append",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccumulatorServer).Append(ctx, req.(*AppendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accumulator_ID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccumulatorServer).ID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accumulator.Accumulator/ID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccumulatorServer).ID(ctx, req.(*IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accumulator_GetProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccumulatorServer).GetProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accumulator.Accumulator/GetProof",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccumulatorServer).GetProof(ctx, req.(*GetProofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Accumulator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "accumulator.Accumulator",
	HandlerType: (*AccumulatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Append",
			Handler:    _Accumulator_Append_Handler,
		},
		{
			MethodName: "ID",
			Handler:    _Accumulator_ID_Handler,
		},
		{
			MethodName: "GetProof",
			Handler:    _Accumulator_GetProof_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accumulator/accumulator.proto",
}
